### ISSUE TITLE
dapp init doesn't play nicely with dapple-quicktest

### ISSUE THREAD

**Issue by apmilen** [dapphub/dapple-quicktest#3]
Dappfile appears screwed up

```
$ dapp init

[. . . write some code . . .]

$ dapple-quicktest
MIGRAE: 0.8.37 - add possible missing fields to Dappfile - authors, licence - Apache-2.0, ...
MIGRAE: 0.8.37 - add ./ prefix to layouts in case its missing
/usr/local/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:29
    dappfile.layout = _.mapValues(dappfile.layout, (path, name) => {
                    ^

TypeError: Cannot create property 'layout' on string 'name            test description version         0.0.1
author          amilenius license         Apache-2.0'
    at migrate (/usr/local/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:29:21)
    at migrate (/usr/local/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:15:7)
    at module.exports (/usr/local/lib/node_modules/dapple/node_modules/dapple-core/local_migration.js:28:3)
    at async.waterfall (/usr/local/lib/node_modules/dapple/node_modules/dapple-core/state.js:56:34)
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:356:16
    at nextTask (/usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:5057:29)
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:5064:13
    at apply (/usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:21:25)
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:56:12
    at /usr/local/lib/node_modules/dapple/node_modules/async/dist/async.js:840:16
dapple-quicktest: Error: Command failed: dapple build --test
```

`dapp init` might not be outputing well formatted yaml?

```
$ cat Dappfile
name            test
description
version         0.0.1

author          amilenius
license         Apache-2.0
```

**Comment by nmushegian** [comment]
Note `dapp` dappfiles are different from `dapple` dappfiles. Ha ha, confusing - this is why I like "erc190.json" as a standalone thing for erc190, etc. I think the plan was to delay naming something the "dappfile" for as long as possible. Did we figure that out yet?

But quicktest in any case shouldn't actually be invoking `dapple build` - so we need to investigate why it is falling back to dapple, not look for how to make dapp generate legacy output

(as an aside, here dapple is trying to migrate your package for dapple compatability, which would still be an error in other contexts even if determine why `dapple build` is being called unnecessarily here. So one workaround would be a --no-migrate flag on dapple)

**Comment by dbrock** [comment]
`dapple-quicktest` without any arguments was made to be the same as `dapple test` so that's for backwards compatibility

the new syntax is `dapple-quicktest <directory>` which is what `dapp test` does (which `make test` is set to invoke by default by `dapp init`)

we should rename `dapple-quicktest` and remove the backwards compatibility code
